pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - '#approved-reviews-by>=1'
      - status-success=continuous-integration/appveyor/pr
      - status-success=continuous-integration/travis-ci/pr
      - 'status-success=LGTM analysis'
      - 'status-success=Codacy/PR Quality Review'
    actions:
      merge:
        method: merge
