branches:
  only:
  - master
  - stable
language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libboost-all-dev  libx11-dev -y
  - export CFLAGS="-m64 -fPIC" && export CXXFLAGS="-m64 -fPIC" && export LDFLAGS="-m64 -fPIC"
  - mkdir _build
  - cd _build
  - cmake .. -DFORCE_OPERATIONS=FALSE -DCLONE_REPO=TRUE -DUSE_BOOST_THREAD=TRUE 

script: cmake --build ../_build --target neon
