branches:
  only:
  - master
language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libboost-all-dev p7zip-full libx11-dev -y
  - export CFLAGS="-m64 -fPIC" && export CXXFLAGS="-m64 -fPIC" && export LDFLAGS="-m64 -fPIC"
  - mkdir _build
  - cd _build
  - cmake ..  -DFORCE_OPERATIONS=TRUE -DDOWNLOAD_SDL2=TRUE

script: cmake --build ../_build --target neon
